### ISSUE TITLE
bro , android is OK ?

### ISSUE THREAD

**Issue by avboy1337** [DoranekoSystems/frida-ceserver#1]
Bro ,so amaziong ,and android is OK ?

**Comment by DoranekoSystems** [comment]
I'll modify it a bit so that it works on Android too.
However, since ceserver exists, it may be less necessary.

**Comment by avboy1337** [comment]
so niubi!!

**Comment by DoranekoSystems** [comment]
The current version seems to work on android as well.
This tool does not require adb forward.
However, the performance will be lower than the original ceserver because the debugger will not work.
