### ISSUE TITLE
How to embed so file into apk

### ISSUE THREAD

**Issue by Thekidiacs** [DoranekoSystems/frida-ceserver#10]
Hi I saw on discord you saying that if ptrace is enabled in game you need to embed the ceserver so file into the apk. Do I need external tools to be able to do that? And if so which one? Thanks.

**Comment by DoranekoSystems** [comment]
If you are doing something somewhat intricate, you will need to be able to do your own research and modify the code.
There are many ways to inject so files via zygisk or by modifying the apk.
The degree of difficulty is relatively high, so it is considered safe to analyze within the scope of existing tools.

**Comment by DoranekoSystems** [comment]
-supplementation-
If you can find out how to make frida-gadget work non-root, it can be done.
Cheat Engine is excellent as a memory analysis tool, although the debugger will not work with the above method.
