### ISSUE TITLE
the latest cheat engine shows error 

### ISSUE THREAD

**Issue by bb33bb** [DoranekoSystems/frida-ceserver#15]
![image](https://github.com/DoranekoSystems/frida-ceserver/assets/5463104/62d69020-e78d-4864-9a55-ca00484b5b4e)

**Comment by DoranekoSystems** [comment]
[frida.general]
ceversion = "7.5.1"

Sorry for the delay in responding.
Please set it to 7.5.1 for patreon's version.
The github one is not supported because the protocol can change.

**Comment by bb33bb** [comment]
is there any patreon's version of [frida-ceserver](https://github.com/DoranekoSystems/frida-ceserver)?
