### ISSUE TITLE
IMPORTANT!

### ISSUE THREAD

**Issue by Thekidiacs** [DoranekoSystems/frida-ceserver#19]
Does this support Dopamine jailbreak? I'm on iOS 16.5 on an arm64e device(iPhone 14 Pro Max). Dopamine Jailbreak is just as powerful as all the other jailbreaks except it doesn't use the root filesystem as its way to jailbreak the device.

**Comment by Thekidiacs** [comment]
My arm64e iPad Pro M1 chip 12.9 on iOS 14.8.1 works just fine with taurine using frida-ceserver. In the meantime I'm going to test my dopamine jailbroken iPhone 14 Pro Max and report back.

**Comment by DoranekoSystems** [comment]
Thank you very much for your comment.
This tool should work on any jailbreak method and device supported by frida.

**Comment by Thekidiacs** [comment]
Just want to say that it works great on my iPhone 14 Pro Max on iOS 16.5! Thank you!
