### ISSUE TITLE
Cannot scan pointer

### ISSUE THREAD

**Issue by 6ag** [DoranekoSystems/frida-ceserver#2]
Thanks, this is a great tool.

I used this ceserver and searched for the data I wanted, but scanning the pointer could not get any results. What do I need to do to get the constant address and offset?

**Comment by 6ag** [comment]
I installed Python and Frida on my Windows computer, and I installed the Frida plug-in on my iPhone. I connected the iPhone to the Windows computer via USB, but after I executed the command, I kept being prompted to wait for the USB device.

```shell
PS E:\frida-ceserver-main> python main.py Cydia
Waiting for usb device...
```

And I can use it normally in MacOS. Can you tell me what should I do?

**Comment by 6ag** [comment]
I installed iTunes and can connect through Cheat Engine. But the ceserver.py script reported an error after a while.

```shell
accept ('127.0.0.1', 58023)
EXCEPTION:CECMD.CMD_READPROCESSMEMORY
Traceback (most recent call last):
  File "E:\frida-ceserver-main\ceserver.py", line 370, in main_thread
    ret = handler(conn,command,thread_count)
  File "E:\frida-ceserver-main\ceserver.py", line 247, in handler
    ret = API.ReadProcessMemory(address,size)
  File "E:\Program Files (x86)\Python37\lib\site-packages\frida\core.py", line 468, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "E:\Program Files (x86)\Python37\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "E:\Program Files (x86)\Python37\lib\site-packages\frida\core.py", line 400, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script has been destroyed
```

**Comment by DoranekoSystems** [comment]
I felt that the pointer scan problem was not valid for normal ceserver as well. 
This may be a bug on the Cheat Engine side.
Does the readprocessmemory error happen again and again?

**Comment by 6ag** [comment]
Yes, on Windows computers, readprocessmemory keeps prompting errors repeatedly. When running the main.py script on a macOS computer, the following error will occasionally appear:

```shell
EXCEPTION:CECMD.CMD_GETSYMBOLLISTFROMFILE
Traceback (most recent call last):
  File "/Users/feng/Downloads/ceserver/ceserver.py", line 369, in main_thread
    b = recvall(conn,1)
  File "/Users/feng/Downloads/ceserver/ceserver.py", line 73, in recvall
    read = s.recv_into(view[pos:], size - pos, flags)
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by DoranekoSystems** [comment]
The problem on Windows may be a problem on the frida side.
I'm trying with frida-14.2.18.
The error problem on Mac is probably caused by my mistake and not closing the socket.
I have made a fixed commit, please try it.

**Comment by 6ag** [comment]
I scan the pointer with 10 levels of offset, and the maximum offset is 20000, but the result is still 0, and the following error keeps recurring:

```shell
accept ('192.168.50.201', 61688)
EXCEPTION:CECMD.CMD_GETVERSION
Traceback (most recent call last):
  File "/Users/feng/Downloads/frida-ceserver-main/ceserver.py", line 368, in main_thread
    b = conn.recv(1)
ConnectionResetError: [Errno 54] Connection reset by peer
accept ('192.168.50.201', 61689)
EXCEPTION:CECMD.CMD_GETVERSION
Traceback (most recent call last):
  File "/Users/feng/Downloads/frida-ceserver-main/ceserver.py", line 368, in main_thread
    b = conn.recv(1)
ConnectionResetError: [Errno 54] Connection reset by peer
accept ('192.168.50.201', 61690)
```

**Comment by 6ag** [comment]
I upgraded the Frida version on my windows computer to 15.0.2, and the ReadProcessMemory error still appears repeatedly.

**Comment by DoranekoSystems** [comment]
Thank you for the confirmation.
At this time, pointer scan is not enabled.
Whether this is a bug in the Cheat Engine or an implementation error on my part is yet to be determined.
The Windows error may be a bit difficult to fix as well.

I have implemented the speedhack feature instead.
Please check it out if you like.

**Comment by 6ag** [comment]
This is very useful for me, thanks again for open source.
I wish you good luck!

**Comment by DoranekoSystems** [comment]
Probably, almost all addresses are determined to be non-static. Therefore, the problem can be solved by including non-static addresses in the search target.

![img](https://user-images.githubusercontent.com/56913432/125820252-23a7f0ff-6338-44df-bf02-1e0fb491bbb9.png)

**Comment by 6ag** [comment]
Thank you very much.
I found a lot of results in your way, and then subtracted the module address from the address of these results to get the static address.
