### ISSUE TITLE
do success?

### ISSUE THREAD

**Issue by mingzizhennanqu** [DoranekoSystems/frida-ceserver#3]
can you speak Chinese?
Can your project capture iOS memory information normally? I recently reverse engineered some iOS projects and need to capture memory information. I have used CE to locate the base address based on winPC. I have not found the corresponding project in iOS. How do I use your project?

**Comment by DoranekoSystems** [comment]
1)Set up frida to be available on iOS.
2)Connect the PC to the iPhone via USB.
Launch iTunes if necessary.

After that, please follow the video.

https://www.youtube.com/watch?v=oDJFc0IgiCc
