### ISSUE TITLE
about the new update

### ISSUE THREAD

**Issue by Thekidiacs** [DoranekoSystems/frida-ceserver#9]
Hey I saw you added floating point debugger support. What does that do? Could you show me a picture maybe :) Thanks.

**Comment by DoranekoSystems** [comment]
Thank you for your comment.
The android version of ceserver now supports floating point registers during debugging in a recent update.
The network protocol has been partially changed, a modification that will work with the latest Cheat Engine.

**Comment by Thekidiacs** [comment]
Sounds great thanks for the info :)
